# Generated by Django 5.1.4 on 2026-03-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('position', 'Position'), ('application', 'Application'), ('contact_form', 'Contact Form')], max_length=20)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('closed', 'Closed'), ('reviewed', 'Reviewed'), ('deleted', 'Deleted'), ('interview', 'Interview'), ('responded', 'Responded')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
