# Generated by Django 5.1.4 on 2026-03-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_jobapplication_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='key_responsibilities',
            field=models.JSONField(default=list, help_text='List of key responsibilities with title and description'),
        ),
        migrations.AddField(
            model_name='position',
            name='role_overview',
            field=models.TextField(default='', help_text='Detailed overview of the role'),
            preserve_default=False,
        ),
    ]
