# Generated by Django 5.1.4 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactsubmission_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('responded', 'Responded'), ('pending', 'Pending'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='contactsubmission',
            unique_together={('email', 'subject')},
        ),
    ]
